name: Metrics â€“ Habits Facts

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  facts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate facts
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 100
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: no
