name: Metrics â€“ Habits

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate habits
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 25
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_skipped: "IssuesEvent,PullRequestEvent,IssueCommentEvent,PullRequestReviewEvent,PullRequestReviewCommentEvent"
          config_timezone: Asia/Irkutsk
